### ISSUE TITLE
菜单项新增加 categories ,tag 无效

### ISSUE THREAD

**Issue by QunxingHu** [yscoder/hexo-theme-indigo#154]
主题下config 修改配置如下：
```
  archives:
    url: /archives
  tags:
    url: /tags
  th-list:
    text: categories
    url: /categories
```
点击菜单项的tag，categories 按钮后，显示的页面内容为空，点击文章的tag 或 categories 是可以分别进入对应 tag, categories页面
