### ISSUE TITLE
[ 强迫症 ] 头像居中与去除白色边框

### ISSUE THREAD

**Issue by Lizhooh** [yscoder/hexo-theme-indigo#169]
1. 在 indigo\source\css\_partial\layout.less 
2. 修改 .brand 

修改为：
```less
    .brand {
        text-align: center;
        padding: 40px @menuPadding 2em;
        background: fade(@primaryColor, 50%);

        > a.avatar {
            margin: 0 auto;
            text-align: center;
            border: none;
        }
    }
```
