### ISSUE TITLE
首页, 左侧头像栏和主页面的背景高度不一致

### ISSUE THREAD

**Issue by ystyle** [yscoder/hexo-theme-indigo#189]
如题

**Comment by yscoder** [comment]
我不认为必须要一致，你可以覆写样式实现一致。

```css
.index-header {
    padding-top: 84px;
}
```
