### ISSUE TITLE
两个小问题，不知道是不是我忽略了什么配置

### ISSUE THREAD

**Issue by haimawudi** [yscoder/hexo-theme-indigo#251]
## 语言问题
某些文字，有时候是英文，有时候是台文，有时候是简体中文。如“知识共享 署名 - 非商业性 - 相同方式共享 4.0 国际协议”，有时候写的是英文的，有时候又是台文，像繁体那种。

## rss
我这rss页面访问都是404，按照您的配置说明。在/hexo/_config.yml配置了
```
feed:
  type: atom
  path: atom.xml
  limit: 0
```
在/hexo/themes/indigo/_config.yml配置了`rss: /atom.xml`

但rss连接到atom.xml是404。[连接](http://mxjhaima.com/atom.xml)
