### ISSUE TITLE
如何添加友情链接

### ISSUE THREAD

**Issue by sshpark** [yscoder/hexo-theme-indigo#255]
在配置文件中没有找到友情链接的配置项，请问该如何添加友情链接呢？

**Comment by reflyhight** [comment]
在/hexo/themes/indigo/_config.yml配置
```
menu:
  home:
    text: 主页
    url: /
  archives:
    text: 时间轴
    url: /archives
  tags:
    text: 标签
    url: /tags
  th-list:
    text: 分类
    url: /categories
  github:
    url: https://github.com/reflyhight
    target: _blank
  weibo:
    url: http://weibo.com/reflyhight
    target: _blank
  link:
    text: 小小默's blog
    url: http://blog.xiaoxiaomo.com/
    target: _blank
```
最后一个整个连接，就行了呗？
