### ISSUE TITLE
如何去掉markdown的行号？

### ISSUE THREAD

**Issue by ryanzhouff** [yscoder/hexo-theme-indigo#325]
不想在markdown格式中显示行号，如图所示：
![noline-number](https://user-images.githubusercontent.com/29921478/31596417-0a706514-b275-11e7-9c9a-76e8350769df.png)

我试图修改配置文件的`highlight`部分:
```yml
highlight:
  enable: true
  line_number: false # 被修改部分
  auto_detect: false
  tab_replace:
```
但是没有成功。有什么办法可以去掉行号？
