### ISSUE TITLE
自定义网页 title

### ISSUE THREAD

**Issue by wencaistorm** [yscoder/hexo-theme-indigo#350]
我想自定义网页 title ，知道是这段代码，但是没找到代码位置。
```js
var OriginTitile = document.title, titleTime;
document.addEventListener('visibilitychange', function() {
	if (document.hidden) {
		document.title = '死鬼去哪里了！';
		clearTimeout(titleTime);
	} else {
		document.title = '(つェ⊂)咦!又好了!';
		titleTime = setTimeout(function() {
			document.title = OriginTitile;
		},2000);
	}
});
```

**Comment by wencaistorm** [comment]
who can tell me please?

**Comment by ckyOL** [comment]
layout/_partial/plugins/dynamic-title.ejs

另想单独禁用title_change.leave一项，由于不懂js只能注释掉。希望能改进此项。

**Comment by wencaistorm** [comment]
*自问自答*
自定义 title ，可在 `_config.yml` 文件中设置：
```yml
# 动态定义title
title_change:
  normal: (つェ⊂)咦!又好了!
  leave: 死鬼去哪里了！
```

**Comment by wencaistorm** [comment]
@ckyOL 
>想单独禁用title_change.leave一项

不是很理解您的意思。
如果希望切换网页时禁止 title 变化，在 `_config.yml` 文件中把下面内容注释掉即可。
```yml
title_change:
  normal: (つェ⊂)咦!又好了!
  leave: 死鬼去哪里了！
```
