### ISSUE TITLE
菜单里面不能添加多个link吗?

### ISSUE THREAD

**Issue by badboy-tian** [yscoder/hexo-theme-indigo#379]
```
link:
    text: 夜明的xxx灯
    url: https://www.xxxx.com/
    target: _blank
  link:
    text: AyoCrazyxxx个人主页
    url: https://www.xxx.com/
    target: _blank
```
这种会报错, 说是link重复了.  我主要是用来添加友链
