### ISSUE TITLE
不知道怎么设置menu的icon

### ISSUE THREAD

**Issue by geekqian** [yscoder/hexo-theme-indigo#404]
完全小白. 看不懂wiki的注释... 
我试过这两种方式都无法编译.  求指导

1 修改 indigo 的 _config.yml
```
menu:
  friends:  user-friends
    text: friends
    url: /friends
```

---

2 在 `theme/indigo/source/css/_partial/fontawesome.less` 添加 
`.@{fa-css-prefix}-friends:before { content: @fa-var-user-friends; }`

![image](https://user-images.githubusercontent.com/15983385/40252563-51f824ce-5b0f-11e8-9504-ea24809d9639.png)

**Comment by yscoder** [comment]
https://fontawesome.com/v4.7.0/icons/
这里能看到图标都可以直接用，也无需定义 less，主题用的是 4.x 版本图标，格式如下：

```yml
[图标]:
  text: [文本]
  url: [链接]
```
