### ISSUE TITLE
如何配置导航栏的ico

### ISSUE THREAD

**Issue by duanyifei1937** [yscoder/hexo-theme-indigo#459]
![image](https://user-images.githubusercontent.com/17761335/52053165-9b73f980-2593-11e9-93e6-faad5b460c5d.png)

themes/indigo/_config.yml:
``` yaml
  books:
    text: Books
    url: /books
```
怎样新引入ico图标呢？
