### ISSUE TITLE
请问有gitment配置的实例，我配了一直抱错

### ISSUE THREAD

**Issue by wubucheng** [yscoder/hexo-theme-indigo#480]
实例,关键信息用xx代替了
```
gitment: true
  gitment:
    owner: xx
    repo: xx
    client_id: xx
    client_secret: xx
```
错误为：YAMLException: bad indentation of a mapping entry at line 110, column 10:
      gitment:
看起来像是语法错误，但是不知如何解决，第二个gitment需要去掉吗？
