### ISSUE TITLE
如果fontawesome里面没有想要的图标怎么办？

### ISSUE THREAD

**Issue by Shineee** [yscoder/hexo-theme-indigo#63]
我在做左侧菜单栏的时候，想添加喜马拉雅，知乎这类连接，但是fontawesome里面没有这种图标怎么办？可以自定义么？

**Comment by yscoder** [comment]
可以，在 css 中按 `.icon-name` 格式添加，以知乎为例：

```css
.icon-zhihu:before {  content: '知' }
```
