### ISSUE TITLE
左侧菜单如何添加category 和 时间归档的目录

### ISSUE THREAD

**Issue by boolBit** [yscoder/hexo-theme-indigo#77]
你好作者，左侧菜单如何添加category 和 时间归档的目录

**Comment by yscoder** [comment]
[参考](https://github.com/yscoder/hexo-theme-indigo/wiki/%E9%85%8D%E7%BD%AE#%E5%B7%A6%E4%BE%A7%E8%8F%9C%E5%8D%95)

### 示例

添加一个链接到 java 分类的菜单项，图标为 coffee。

```yml
menu:
  coffee:
    text: java
    url: /categories/java
```
